<?php

return [
  // Lista corta y práctica de Material Icons (nombres) para autocompletar en el panel.
  // Puedes agregar más cuando lo necesites.
  'icons' => [
    // Básicos
    'star',
    'favorite',
    'thumb_up',
    'done',
    'done_all',
    'check',
    'close',
    'warning',
    'error',
    'help_outline',
    'info',
    'image',
    'chevron_left',
    'chevron_right',
    'expand_more',
    'expand_less',
    'edit',
    'delete',
    'add',
    'remove',
    'search',
    'filter_alt',
    'tune',
    'category',
    'apps',
    'more_vert',
    'open_in_new',
    'link',
    'share',

    // Textil / servicios
    'print',
    'gesture',
    'palette',
    'color_lens',
    'brush',
    'format_paint',
    'checkroom',
    'straighten',
    'verified',
    'local_offer',
    'sell',
    'loyalty',
    'workspace_premium',
    'military_tech',
    'emoji_events',
    'inventory',
    'inventory_2',
    'precision_manufacturing',
    'factory',
    'handyman',
    'build',
    'construction',
    'design_services',

    // Negocio / contacto
    'phone',
    'call',
    'email',
    'alternate_email',
    'location_on',
    'support_agent',
    'headset_mic',
    'chat',
    'forum',
    'send',
    'apartment',
    'storefront',
    'store',
    'groups',
    'handshake',
    'badge',
    'work',
    'business',

    // Logística / tiempo
    'local_shipping',
    'schedule',
    'history',
    'event',
    'calendar_today',
    'timer',
    'warehouse',

    // Eventos / deporte / seguridad
    'fitness_center',
    'shield',
    'security',
    'verified_user',

    // Social / web
    'photo_camera',
    'language',
    'public',

    // UI
    'shopping_bag',
    'local_mall',
    'admin_panel_settings',
    'settings',
    'visibility',
    'visibility_off',
    'download',
    'upload',
    'cloud_upload',
    'attach_file',
    'qr_code',
  ],
];
